### PR TITLE
Versioning adjustments

### LINKED ISSUE #19: Undefined index: version - Exception is thrown in v4.0.0-beta.2
**Exception message:**
```
1 exception(s):
Exception #0 (SwedbankPay\Core\Exception\ClientException): Exception: Notice: Undefined index: version in /home/danieln7/staging/vendor/swedbank-pay/swedbank-pay-sdk-php/src/SwedbankPay/Api/Client/Client.php on line 67 in /home/danieln7/staging/vendor/magento/framework/App/ErrorHandler.php:61
```

**Line that caused the exception:**
https://github.com/SwedbankPay/swedbank-pay-sdk-php/blob/v4.0.0-beta.2/src/SwedbankPay/Api/Client/Client.php#L65

**Reason:**
Version does not exist in the `composer.json` file

### PR DESCRIPTION
**Pull request by asbjornu**
This PR adds a `Dockerfile` which reproduces the problem with missing `VERSION` reported in #19.

Fixes #19 by looking for `version` in the `composer.lock` file of the SDK-consuming application.

### CODE REVIEW

File: tests/sdk-consumer/app.php [hunk 1]
```diff
@@ -0,0 +1,12 @@
+<?php
+
+require_once __DIR__ . '/vendor/autoload.php';
```
Comment (payex-dev) [inline tests/sdk-consumer/app.php:3]: Codacy Issue found: ["require_once" statement detected. File manipulations are discouraged. Concatenating is forbidden.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907&bid=17360395)

File: tests/sdk-consumer/app.php [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+
+use \SwedbankPay\Api\Client;
+
+$client = new \SwedbankPay\Api\Client\Client();
+$version = new \SwedbankPay\Api\Client\Version();
+
+var_dump($version->getVersion());
```
Comment (payex-dev) [inline tests/sdk-consumer/app.php:10]: Codacy Issue found: [The use of function var_dump() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Client/Version.php  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907&bid=17360395)

File: tests/sdk-consumer/app.php (hunk 2 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:10]: Codacy Issue found: [The use of function var_dump() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 1 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:3]: Codacy Issue found: ["require_once" statement detected. File manipulations are discouraged. Concatenating is forbidden.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Client/Version.php  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907&bid=17360395)

File: tests/sdk-consumer/app.php (hunk 2 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:10]: Codacy Issue found: [The use of function var_dump() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 1 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:3]: Codacy Issue found: ["require_once" statement detected. File manipulations are discouraged. Concatenating is forbidden.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Api/Client/Version.php [hunk 3]
```diff
@@ -48,14 +50,42 @@ protected function getVersionFromEnvironment()
...
+
+    /**
+     * Reads the file at $path and returns it as a JSON decoded object.
+     *
+     * @param $path The path of the file to read and JSON decode.
+     * @return object The JSON decoded object.
+     */
+    private function readJson($path)
+    {
+        $path =  realpath($path);
```
Comment (payex-dev) [inline src/SwedbankPay/Api/Client/Version.php:87]: Codacy Issue found: [The use of function realpath() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Client/Version.php  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907&bid=17360395)

File: src/SwedbankPay/Api/Client/Version.php [hunk 4]
```diff
@@ -48,14 +50,76 @@ protected function getVersionFromEnvironment()
...
+
+
+    /**
+    * This function is to replace PHP's extremely buggy realpath().
+    * https://stackoverflow.com/a/4050444/61818
+    *
+    * @param string The original path, can be relative etc.
+    * @return string The resolved path, it might not exist.
+    */
+    private function truePath($path){
```
Comment (payex-dev) [inline src/SwedbankPay/Api/Client/Version.php:100]: Codacy Issue found: [The method truePath() has a Cyclomatic Complexity of 10. The configured cyclomatic complexity threshold is 10.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 2 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:10]: Codacy Issue found: [The use of function var_dump() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 1 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:3]: Codacy Issue found: ["require_once" statement detected. File manipulations are discouraged. Concatenating is forbidden.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Api/Client/Version.php [hunk 5]
```diff
@@ -48,14 +50,76 @@ protected function getVersionFromEnvironment()
...
+            $path=getcwd().DIRECTORY_SEPARATOR.$path;
+        // resolve path parts (single dot, double dot and double delimiters)
+        $path = str_replace(array('/', '\\'), DIRECTORY_SEPARATOR, $path);
+        $parts = array_filter(explode(DIRECTORY_SEPARATOR, $path), 'strlen');
+        $absolutes = array();
+        foreach ($parts as $part) {
+            if ('.'  == $part) continue;
+            if ('..' == $part) {
+                array_pop($absolutes);
+            } else {
```
Comment (payex-dev) [inline src/SwedbankPay/Api/Client/Version.php:114]: Codacy Issue found: [The method getVersion uses an else expression. Else clauses are basically not necessary and you can simplify the code by not using them.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Api/Client/Version.php [hunk 6]
```diff
@@ -48,14 +50,76 @@ protected function getVersionFromEnvironment()
...
+                $absolutes[] = $part;
+            }
+        }
+        $path=implode(DIRECTORY_SEPARATOR, $absolutes);
+        // resolve any symlinks
+        if(file_exists($path) && linkinfo($path)>0)$path=readlink($path);
```
Comment (payex-dev) [inline src/SwedbankPay/Api/Client/Version.php:120]: Codacy Issue found: [The use of function readlink() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Client/Version.php  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907&bid=17360395)

File: src/SwedbankPay/Api/Client/Version.php [hunk 7]
```diff
@@ -48,14 +50,91 @@ protected function getVersionFromEnvironment()
...
+            } else {
+                $absolutes[] = $part;
+            }
+        }
+
+        $path = implode(DIRECTORY_SEPARATOR, $absolutes);
+
+        // resolve any symlinks
+        if (file_exists($path) && linkinfo($path) > 0) {
+            $path = readlink($path);
```
Comment (payex-dev) [inline src/SwedbankPay/Api/Client/Version.php:132]: Codacy Issue found: [The use of function readlink() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Api/Client/Version.php [hunk 8]
```diff
@@ -48,14 +50,91 @@ protected function getVersionFromEnvironment()
...
+                array_pop($absolutes);
+            } else {
+                $absolutes[] = $part;
+            }
+        }
+
+        $path = implode(DIRECTORY_SEPARATOR, $absolutes);
+
+        // resolve any symlinks
+        if (file_exists($path) && linkinfo($path) > 0) {
```
Comment (payex-dev) [inline src/SwedbankPay/Api/Client/Version.php:131]: Codacy Issue found: [The use of function linkinfo() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 2 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:10]: Codacy Issue found: [The use of function var_dump() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Api/Client/Version.php [hunk 9]
```diff
@@ -48,14 +50,91 @@ protected function getVersionFromEnvironment()
...
+
+
+    /**
+    * This function is to replace PHP's extremely buggy realpath().
+    * https://stackoverflow.com/a/4050444/61818
+    *
+    * @param string The original path, can be relative etc.
+    * @return string The resolved path, it might not exist.
+    */
+    private function truePath($path){
```
Comment (payex-dev) [inline src/SwedbankPay/Api/Client/Version.php:102]: Codacy Issue found: [The method truePath() has a Cyclomatic Complexity of 10. The configured cyclomatic complexity threshold is 10.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Api/Client/Version.php [hunk 10]
```diff
@@ -48,14 +50,91 @@ protected function getVersionFromEnvironment()
...
+        $absolutes = array();
+
+        foreach ($parts as $part) {
+            if ('.'  == $part) {
+                continue;
+            }
+
+            if ('..' == $part) {
+                array_pop($absolutes);
+            } else {
```
Comment (payex-dev) [inline src/SwedbankPay/Api/Client/Version.php:123]: Codacy Issue found: [The method getVersion uses an else expression. Else clauses are basically not necessary and you can simplify the code by not using them.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 1 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:3]: Codacy Issue found: ["require_once" statement detected. File manipulations are discouraged. Concatenating is forbidden.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 7
           

Complexity increasing per file
==============================
- tests/PathTest.php  1
- src/SwedbankPay/Api/Client/Version.php  4
- src/SwedbankPay/Path.php  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907&bid=17360395)

File: src/SwedbankPay/Path.php [hunk 11]
```diff
@@ -0,0 +1,56 @@
...
+            } else {
+                $absolutes[] = $part;
+            }
+        }
+
+        $path = implode(DIRECTORY_SEPARATOR, $absolutes);
+
+        // resolve any symlinks
+        if (file_exists($path) && linkinfo($path) > 0) {
+            $path = readlink($path);
```
Comment (payex-dev) [inline src/SwedbankPay/Path.php:45]: Codacy Issue found: [The use of function readlink() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 2 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:10]: Codacy Issue found: [The use of function var_dump() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/PathTest.php [hunk 12]
```diff
@@ -0,0 +1,14 @@
+<?php
+
+class PathTest extends \PHPUnit\Framework\TestCase
+{
+    public function testResolve() : void
+    {
+        $path = __DIR__ . '/../src/SwedbankPay/Api/../';
+        $resolvedPath = \SwedbankPay\Path::resolve($path);
```
Comment (payex-dev) [inline tests/PathTest.php:8]: Codacy Issue found: [Avoid using static access to class '\SwedbankPay\Path' in method 'testResolve'.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 1 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:3]: Codacy Issue found: ["require_once" statement detected. File manipulations are discouraged. Concatenating is forbidden.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Path.php [hunk 13]
```diff
@@ -0,0 +1,56 @@
...
+class Path
+{
+        /**
+    * This function is to replace PHP's extremely buggy realpath().
+    * https://stackoverflow.com/a/4050444/61818
+    *
+    * @param string The original path, can be relative etc.
+    * @return string The resolved path, it might not exist.
+    */
+    public static function resolve($path)
```
Comment (payex-dev) [inline src/SwedbankPay/Path.php:14]: Codacy Issue found: [The method resolve() has a Cyclomatic Complexity of 10. The configured cyclomatic complexity threshold is 10.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Path.php [hunk 14]
```diff
@@ -0,0 +1,56 @@
...
+        $absolutes = array();
+
+        foreach ($parts as $part) {
+            if ('.'  == $part) {
+                continue;
+            }
+
+            if ('..' == $part) {
+                array_pop($absolutes);
+            } else {
```
Comment (payex-dev) [inline src/SwedbankPay/Path.php:36]: Codacy Issue found: [The method resolve uses an else expression. Else clauses are basically not necessary and you can simplify the code by not using them.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Path.php [hunk 15]
```diff
@@ -0,0 +1,56 @@
...
+                $absolutes[] = $part;
+            }
+        }
+
+        $path = implode(DIRECTORY_SEPARATOR, $absolutes);
+
+        // resolve any symlinks
+        if (file_exists($path) && linkinfo($path) > 0) {
```
Comment (payex-dev) [inline src/SwedbankPay/Path.php:44]: Codacy Issue found: [The use of function linkinfo() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 8
           

Complexity increasing per file
==============================
- tests/PathTest.php  1
- src/SwedbankPay/Path.php  7
- src/SwedbankPay/Api/Client/Version.php  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907&bid=17360395)

File: src/SwedbankPay/Path.php (hunk 15 above)
Comment (payex-dev) [inline src/SwedbankPay/Path.php:44]: Codacy Issue found: [The use of function linkinfo() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Api/Client/Version.php [hunk 16]
```diff
@@ -48,14 +50,44 @@ protected function getVersionFromEnvironment()
...
+
+    /**
+     * Reads the file at $path and returns it as a JSON decoded object.
+     *
+     * @param $path The path of the file to read and JSON decode.
+     * @return object The JSON decoded object.
+     */
+    private function readJson($path)
+    {
+        $path = \SwedbankPay\Path::resolve($path);
```
Comment (payex-dev) [inline src/SwedbankPay/Api/Client/Version.php:89]: Codacy Issue found: [Avoid using static access to class '\SwedbankPay\Path' in method 'readJson'.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 1 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:3]: Codacy Issue found: ["require_once" statement detected. File manipulations are discouraged. Concatenating is forbidden.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Path.php (hunk 11 above)
Comment (payex-dev) [inline src/SwedbankPay/Path.php:45]: Codacy Issue found: [The use of function readlink() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/PathTest.php (hunk 12 above)
Comment (payex-dev) [inline tests/PathTest.php:8]: Codacy Issue found: [Avoid using static access to class '\SwedbankPay\Path' in method 'testResolve'.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Path.php (hunk 13 above)
Comment (payex-dev) [inline src/SwedbankPay/Path.php:14]: Codacy Issue found: [The method resolve() has a Cyclomatic Complexity of 10. The configured cyclomatic complexity threshold is 10.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 2 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:10]: Codacy Issue found: [The use of function var_dump() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Path.php (hunk 14 above)
Comment (payex-dev) [inline src/SwedbankPay/Path.php:36]: Codacy Issue found: [The method resolve uses an else expression. Else clauses are basically not necessary and you can simplify the code by not using them.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 8
           

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Client/Version.php  4
- tests/PathTest.php  1
- src/SwedbankPay/Path.php  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907&bid=17360395)

File: src/SwedbankPay/Path.php [hunk 17]
```diff
@@ -0,0 +1,55 @@
...
+        $absolutes = array();
+
+        foreach ($parts as $part) {
+            if ('.'  == $part) {
+                continue;
+            }
+
+            if ('..' == $part) {
+                array_pop($absolutes);
+            } else {
```
Comment (payex-dev) [inline src/SwedbankPay/Path.php:36]: Codacy Issue found: [The method resolve uses an else expression. Else clauses are basically not necessary and you can simplify the code by not using them.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Api/Client/Version.php (hunk 16 above)
Comment (payex-dev) [inline src/SwedbankPay/Api/Client/Version.php:89]: Codacy Issue found: [Avoid using static access to class '\SwedbankPay\Path' in method 'readJson'.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Path.php [hunk 18]
```diff
@@ -0,0 +1,55 @@
...
+                $absolutes[] = $part;
+            }
+        }
+
+        $path = implode(DIRECTORY_SEPARATOR, $absolutes);
+
+        // resolve any symlinks
+        if (file_exists($path) && linkinfo($path) > 0) {
+            $path = readlink($path);
```
Comment (payex-dev) [inline src/SwedbankPay/Path.php:45]: Codacy Issue found: [The use of function readlink() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Path.php [hunk 19]
```diff
@@ -0,0 +1,55 @@
...
+class Path
+{
+        /**
+    * This function is to replace PHP's extremely buggy realpath().
+    * https://stackoverflow.com/a/4050444/61818
+    *
+    * @param string The original path, can be relative etc.
+    * @return string The resolved path, it might not exist.
+    */
+    public static function resolve($path)
```
Comment (payex-dev) [inline src/SwedbankPay/Path.php:14]: Codacy Issue found: [The method resolve() has a Cyclomatic Complexity of 10. The configured cyclomatic complexity threshold is 10.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Path.php [hunk 20]
```diff
@@ -0,0 +1,55 @@
...
+                array_pop($absolutes);
+            } else {
+                $absolutes[] = $part;
+            }
+        }
+
+        $path = implode(DIRECTORY_SEPARATOR, $absolutes);
+
+        // resolve any symlinks
+        if (file_exists($path) && linkinfo($path) > 0) {
```
Comment (payex-dev) [inline src/SwedbankPay/Path.php:44]: Codacy Issue found: [The use of function linkinfo() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/PathTest.php (hunk 12 above)
Comment (payex-dev) [inline tests/PathTest.php:8]: Codacy Issue found: [Avoid using static access to class '\SwedbankPay\Path' in method 'testResolve'.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 1 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:3]: Codacy Issue found: ["require_once" statement detected. File manipulations are discouraged. Concatenating is forbidden.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 2 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:10]: Codacy Issue found: [The use of function var_dump() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 8
           

Complexity increasing per file
==============================
- src/SwedbankPay/Api/Client/Version.php  4
- src/SwedbankPay/Path.php  7
- tests/PathTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907&bid=17360395)

File: src/SwedbankPay/Path.php [hunk 21]
```diff
@@ -0,0 +1,53 @@
...
+class Path
+{
+        /**
+    * This function is to replace PHP's extremely buggy realpath().
+    * https://stackoverflow.com/a/4050444/61818
+    *
+    * @param string The original path, can be relative etc.
+    * @return string The resolved path, it might not exist.
+    */
+    public static function resolve($path)
```
Comment (payex-dev) [inline src/SwedbankPay/Path.php:14]: Codacy Issue found: [The method resolve() has a Cyclomatic Complexity of 10. The configured cyclomatic complexity threshold is 10.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 1 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:3]: Codacy Issue found: ["require_once" statement detected. File manipulations are discouraged. Concatenating is forbidden.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/PathTest.php (hunk 12 above)
Comment (payex-dev) [inline tests/PathTest.php:8]: Codacy Issue found: [Avoid using static access to class '\SwedbankPay\Path' in method 'testResolve'.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Path.php [hunk 22]
```diff
@@ -0,0 +1,53 @@
...
+                array_pop($absolutes);
+            } else {
+                $absolutes[] = $part;
+            }
+        }
+
+        $path = implode(DIRECTORY_SEPARATOR, $absolutes);
+
+        // resolve any symlinks
+        if (file_exists($path) && linkinfo($path) > 0) {
```
Comment (payex-dev) [inline src/SwedbankPay/Path.php:44]: Codacy Issue found: [The use of function linkinfo() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Api/Client/Version.php (hunk 16 above)
Comment (payex-dev) [inline src/SwedbankPay/Api/Client/Version.php:89]: Codacy Issue found: [Avoid using static access to class '\SwedbankPay\Path' in method 'readJson'.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Path.php [hunk 23]
```diff
@@ -0,0 +1,53 @@
...
+        $absolutes = array();
+
+        foreach ($parts as $part) {
+            if ('.'  == $part) {
+                continue;
+            }
+
+            if ('..' == $part) {
+                array_pop($absolutes);
+            } else {
```
Comment (payex-dev) [inline src/SwedbankPay/Path.php:36]: Codacy Issue found: [The method resolve uses an else expression. Else clauses are basically not necessary and you can simplify the code by not using them.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 2 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:10]: Codacy Issue found: [The use of function var_dump() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Path.php [hunk 24]
```diff
@@ -0,0 +1,53 @@
...
+                $absolutes[] = $part;
+            }
+        }
+
+        $path = implode(DIRECTORY_SEPARATOR, $absolutes);
+
+        // resolve any symlinks
+        if (file_exists($path) && linkinfo($path) > 0) {
+            $path = readlink($path);
```
Comment (payex-dev) [inline src/SwedbankPay/Path.php:45]: Codacy Issue found: [The use of function readlink() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Complexity increasing per file
==============================
- src/SwedbankPay/Path.php  7
- src/SwedbankPay/Api/Client/Version.php  4
- tests/PathTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907&bid=17360395)

File: tests/sdk-consumer/app.php (hunk 2 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:10]: Codacy Issue found: [The use of function var_dump() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 1 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:3]: Codacy Issue found: ["require_once" statement detected. File manipulations are discouraged. Concatenating is forbidden.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Path.php [hunk 25]
```diff
@@ -0,0 +1,53 @@
...
+class Path
+{
+        /**
+    * This function is to replace PHP's extremely buggy realpath().
+    * https://stackoverflow.com/a/4050444/61818
+    *
+    * @param string The original path, can be relative etc.
+    * @return string The resolved path, it might not exist.
+    */
+    public function resolve($path)
```
Comment (payex-dev) [inline src/SwedbankPay/Path.php:14]: Codacy Issue found: [The method resolve() has a Cyclomatic Complexity of 10. The configured cyclomatic complexity threshold is 10.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Path.php [hunk 26]
```diff
@@ -0,0 +1,53 @@
...
+                array_pop($absolutes);
+            } else {
+                $absolutes[] = $part;
+            }
+        }
+
+        $path = implode(DIRECTORY_SEPARATOR, $absolutes);
+
+        // resolve any symlinks
+        if (file_exists($path) && linkinfo($path) > 0) {
```
Comment (payex-dev) [inline src/SwedbankPay/Path.php:44]: Codacy Issue found: [The use of function linkinfo() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Path.php [hunk 27]
```diff
@@ -0,0 +1,53 @@
...
+            $path = readlink($path);
```
Comment (payex-dev) [inline src/SwedbankPay/Path.php:45]: Codacy Issue found: [The use of function readlink() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/Path.php [hunk 28]
```diff
@@ -0,0 +1,53 @@
...
+        $absolutes = array();
+
+        foreach ($parts as $part) {
+            if ('.'  == $part) {
+                continue;
+            }
+
+            if ('..' == $part) {
+                array_pop($absolutes);
+            } else {
```
Comment (payex-dev) [inline src/SwedbankPay/Path.php:36]: Codacy Issue found: [The method resolve uses an else expression. Else clauses are basically not necessary and you can simplify the code by not using them.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 2 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:10]: Codacy Issue found: [The use of function var_dump() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- tests/PathResolverTest.php  1
- src/SwedbankPay/Api/Client/Version.php  4
- src/SwedbankPay/PathResolver.php  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907&bid=17360395)

File: tests/sdk-consumer/app.php (hunk 1 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:3]: Codacy Issue found: ["require_once" statement detected. File manipulations are discouraged. Concatenating is forbidden.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/PathResolver.php [hunk 29]
```diff
@@ -0,0 +1,138 @@
...
+
+    /**
+     * Resolve any symbolic links in the path.
+     *
+     * @param string $path The in which to resolve symbolic links.
+     * @return string The resolved path.
+     */
+    private function resolveSymlinks($path) : string
+    {
+        if (file_exists($path) && linkinfo($path) > 0) {
```
Comment (payex-dev) [inline src/SwedbankPay/PathResolver.php:98]: Codacy Issue found: [The use of function linkinfo() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/PathResolver.php [hunk 30]
```diff
@@ -0,0 +1,138 @@
...
+            return readlink($path);
```
Comment (payex-dev) [inline src/SwedbankPay/PathResolver.php:99]: Codacy Issue found: [The use of function readlink() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 8
           

Complexity increasing per file
==============================
- src/SwedbankPay/PathResolver.php  5
- tests/PathResolverTest.php  1
- src/SwedbankPay/Api/Client/Version.php  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907&bid=17360395)

File: tests/sdk-consumer/app.php [hunk 31]
```diff
@@ -0,0 +1,13 @@
+<?php
+
+require_once __DIR__ . '/vendor/autoload.php';
```
Comment (payex-dev) [inline tests/sdk-consumer/app.php:3]: Codacy Issue found: ["require_once" statement detected. File manipulations are discouraged. Concatenating is forbidden.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php [hunk 32]
```diff
@@ -0,0 +1,13 @@
...
+
+use \SwedbankPay\Api\Client;
+
+$client = new \SwedbankPay\Api\Client\Client();
+$version = new \SwedbankPay\Api\Client\Version();
+
+$v = $version->getVersion();
+echo "version: $v";
```
Comment (payex-dev) [inline tests/sdk-consumer/app.php:11]: Codacy Issue found: [Use of echo language construct is discouraged.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/PathResolver.php [hunk 33]
```diff
@@ -0,0 +1,157 @@
...
+    }
+
+
+    /**
+      * Makes the directories (parts) of the path absolute.
+      *
+      * @param string $path The path to make absolute.
+      * @return string The absolute path.
+      */
+    private function absolutizeParts($path) : string
```
Comment (payex-dev) [inline src/SwedbankPay/PathResolver.php:87]: Codacy Issue found: [Avoid unused private methods such as 'absolutizeParts'.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/PathResolver.php [hunk 34]
```diff
@@ -0,0 +1,157 @@
...
+    /**
+     * Resolve any symbolic links in the path.
+     *
+     * @param string $path The in which to resolve symbolic links.
+     * @return string The resolved path.
+     */
+    private function resolveSymlinks($path) : string
+    {
+        if (file_exists($path) && linkinfo($path) > 0) {
+            return readlink($path);
```
Comment (payex-dev) [inline src/SwedbankPay/PathResolver.php:118]: Codacy Issue found: [The use of function readlink() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/PathResolver.php [hunk 35]
```diff
@@ -0,0 +1,157 @@
...
+
+    /**
+     * Resolve any symbolic links in the path.
+     *
+     * @param string $path The in which to resolve symbolic links.
+     * @return string The resolved path.
+     */
+    private function resolveSymlinks($path) : string
+    {
+        if (file_exists($path) && linkinfo($path) > 0) {
```
Comment (payex-dev) [inline src/SwedbankPay/PathResolver.php:117]: Codacy Issue found: [The use of function linkinfo() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/PathResolver.php [hunk 36]
```diff
@@ -0,0 +1,157 @@
...
+        $absolutes = array();
+
+        foreach ($parts as $part) {
+            if ('.'  == $part) {
+                continue;
+            }
+
+            if ('..' == $part) {
+                array_pop($absolutes);
+            } else {
```
Comment (payex-dev) [inline src/SwedbankPay/PathResolver.php:100]: Codacy Issue found: [The method resolve uses an else expression. Else clauses are basically not necessary and you can simplify the code by not using them.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/PathResolver.php [hunk 37]
```diff
@@ -0,0 +1,157 @@
...
+    }
+
+
+    /**
+      * Ensure that the path is rooted.
+      *
+      * @param string $path The potentially unrooted path.
+      * @return string The rooted path.
+      */
+    private function root($path) : string
```
Comment (payex-dev) [inline src/SwedbankPay/PathResolver.php:131]: Codacy Issue found: [Avoid unused private methods such as 'root'.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 32 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:11]: Codacy Issue found: [All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '"version: $v"'.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- src/SwedbankPay/PathResolver.php  4
- src/SwedbankPay/Api/Client/Version.php  4
- tests/PathResolverTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907&bid=17360395)

File: src/SwedbankPay/PathResolver.php [hunk 38]
```diff
@@ -0,0 +1,139 @@
...
+    /**
+     * Resolve any symbolic links in the path.
+     *
+     * @param string $path The in which to resolve symbolic links.
+     * @return string The resolved path.
+     */
+    private function resolveSymlinks($path) : string
+    {
+        if (file_exists($path) && linkinfo($path) > 0) {
+            return readlink($path);
```
Comment (payex-dev) [inline src/SwedbankPay/PathResolver.php:101]: Codacy Issue found: [The use of function readlink() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 32 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:11]: Codacy Issue found: [All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '"version: $v"'.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

Comment (payex-dev) [inline tests/sdk-consumer/app.php:11]: Codacy Issue found: [Use of echo language construct is discouraged.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: tests/sdk-consumer/app.php (hunk 31 above)
Comment (payex-dev) [inline tests/sdk-consumer/app.php:3]: Codacy Issue found: ["require_once" statement detected. File manipulations are discouraged. Concatenating is forbidden.](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

File: src/SwedbankPay/PathResolver.php [hunk 39]
```diff
@@ -0,0 +1,139 @@
...
+
+    /**
+     * Resolve any symbolic links in the path.
+     *
+     * @param string $path The in which to resolve symbolic links.
+     * @return string The resolved path.
+     */
+    private function resolveSymlinks($path) : string
+    {
+        if (file_exists($path) && linkinfo($path) > 0) {
```
Comment (payex-dev) [inline src/SwedbankPay/PathResolver.php:100]: Codacy Issue found: [The use of function linkinfo() is discouraged](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/PathResolverTest.php  1
- src/SwedbankPay/Api/Client/Version.php  4
- src/SwedbankPay/PathResolver.php  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907&bid=17360395)

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/PathResolverTest.php  1
- src/SwedbankPay/Api/Client/Version.php  4
- src/SwedbankPay/PathResolver.php  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-sdk-php/pullRequest?prid=5303907&bid=17360395)
